image: docker:latest

variables:
  REPOSITORY_URL: ranggakrisna/todos-api
  IMAGE_TAG: latest

services:
  - docker:dind

before_script:
  - docker login --username=$DH_USERNAME --password=$DH_PASSWORD

stages:
  - build
  - deploy
  - test

build:
  stage: build
  script:
    - echo "Building image..."
    - docker build
      -t todos-api:latest
      --build-arg PORT=$PORT
      --no-cache .
    - echo "Tagging image..."
    - docker tag todos-api:latest $REPOSITORY_URL:latest
    - echo "Pushing image..."
    - docker push $REPOSITORY_URL:latest
  only:
    - main

deploy:
  stage: deploy
  script:
    - docker stop todos-api || true && docker rm todos-api || true
    - docker container run -dt -p $PORT:$PORT --name todos-api $REPOSITORY_URL:latest
  only:
    - main

test:
  stage: test
  script:
    - npm install jest supertest
    - NODE_ENV=test && jest --detectOpenHandles --runInBand --forceExit --watchAll --coverage --verbose
  artifacts:
    when: always
    paths:
      - ./test/todo.test.js
  only:
    - main
